export const topicPages = [{
  page: "Home",
  title: "Science of Reading--Caring",
  challenge: "Not everyone is cut out to care this much.",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Baseball",
  title: "Science of Reading--The Baseball Study",
  challenge: "The Science of Reading is far, far moe than just phonics.",
  pageXPs: ["XP5", "XP6"],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "RocketScience",
  title: "Science of Reading--Is Rocket Science",
  challenge: "Teaching Reading is Hard. Rocket Science Hard.",
  pageXPs: [],
  text1: "We must do all we can to make it easier for mere mortals.",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "RowsIsRose",
  title: "Science of Reading--RowsIsRose",
  challenge: "What's Going On in His Head?",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Comprehension",
  title: "Science of Reading--Comprehension",
  challenge: "Is Reading Comprension A Skill?",
  pageXPs: [],
  text1: "",
  text2: "Comprehension instruction IS NOT worksheets with Find the Main Idea. ",
  text3: "Comprehension instruction IS done within a comprehensive high quality curriculum, with proper training of teachers, employing a number of proven reading strategies.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "KnowledgeCurse",
  title: "Science of Reading--The Curse of Knowledge",
  challenge: "What is the Curse of Knowledge?",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "StructuredLit",
  title: "Science of Reading--Structured Literacy",
  challenge: "Foundations",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Improvement",
  title: "Science of Reading--Room to Improve",
  challenge: "Could Many More Kids Really be Learning to Read?",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Decoding",
  title: "Science of Reading--Decoding",
  challenge: "Decoding. (Do Schools Teach Phonics?)",
  pageXPs: ["XP29", "XP30", "XP31", "XP32", "XP101", "XP102", "XP103"],
  text1: "We'll get much more into this in Level 2.",
  text2: "For now, a few introductory things to help those on the new side of things.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Morphology",
  title: "Science of Reading--Morphology",
  challenge: "Why Is Morphology for Power Readers (Plus All the Rest)?",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Dyslexia",
  title: "Science of Reading--Dyslexia + DLD",
  challenge: "What Should Parents and Teachers Know of Dyslexia? And how is it different from DLD?",
  text1: "DLDs are actually more common than devlopmental dyslexia.",
  text2: "",
  text3: "",
  pageXPs: ["XP6101"],
  use_sections: true,
  sectionInfo: [{
    sectionHeading: "Developmental Language Disorders",
    sectionText1: "When children have issues with languge comprehension--not word recognition, but with understanding language, ",
    sectionText2: "DLDs affect how children learn to read.",
    sectionText3: "",
    sectionXPs: ["XP6105", "XP6106"]
  },
  {
    sectionHeading: "Dyslexia: Word-level Difficulties ",
    sectionText1: "Rougly one in sixteen children come to school with developmental dyslexia conditions.",
    sectionText2: "",
    sectionText3: "",
    sectionXPs: ["XP9", "XP10", "XP11", "XP12"]
  }],
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Curriculum",
  title: "Science of Reading--Curriculum",
  challenge: "So which curricula really work?",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Fluency",
  title: "Science of Reading--Fluency",
  challenge: "Why Does Fluency Training Get a Bad Rap?",
  pageXPs: ["XP50", "XP51", "XP56", "XP52", "XP53", "XP54", "XP57"],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "", modal: ""
}, {
  page: "EdSchools",
  title: "Science of Reading--Schools of Education",
  challenge: "Are Ed Schools Helping? Or Hurting?",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Poverty",
  title: "Science of Reading--Poverty",
  challenge: "But, Poverty",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Writing",
  title: "Science of Reading--Writing",
  challenge: "Writing for Reading",
  use_sections: "false",
  pageXPs: ["XP124", "XP120", "XP121", "XP122"],
  text1: "Teaching students to write clear, interesting sentences is crucial to teaching them how to be good, competant readers. ",
  text2: "It was hard to leave this out of Level One. The fundamental insight certainly belongs there.",
  text3: "To clearly explain this, we have to get into details of practice.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "BadUgly",
  title: "Science of Reading--Good, Bad, Ugly",
  challenge: "Curriculum: The Good, the Bad, and the Ugly.",
  pageXPs: ["XP112", "XP113", "XP5670", "XP5610", "XP117", "XP111", "XP119"],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Kindergarten",
  title: "Science of Reading--Kindergarten",
  challenge: "How Can Teachers of the Littlest Improve their Reading Readiness?",
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "MiddleSchool",
  title: "Science of Reading--Middle School",
  challenge: "Middle School",
  pageXPs: [],
  text1: "S.O.R. definitely isn't just for K-2! So how can the Science of Reading help us improve life for middle school students?",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "See our `Writing` page for more help.",
  modal: ""
}, {
  page: "HighSchool",
  title: "Science of Reading--High School",
  challenge: "High School",
  pageXPs: ["XP182", "XP186", "XP183", "XP180", "XP181", "XP185", "XP184"],
  text1: "Can the Science of reading still improve life for high school teens?",
  text2: "",
  text3: "",
  closingText: "As with middle school, see the Writing page here for ideas on applying S.o.R. in general class work.",
  closingText2: "And see the Interventions page for more ideas on helping kids catch up with reading basics.",
  modal: ""
}, {
  page: "TeachingArts",
  title: "Arts of Teaching",
  challenge: "What Are Some Arts of Teaching Reading?",
  pageXPs: [],
  text1: "All teachers are artists.",
  text2: "While Science doesn't back teaching to Learning Styles, good teachers reinforce learning with a wide range of artistic tools.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "ELABlock",
  title: "Building the ELA Block/Day",
  challenge: "Squeezing the Most out of Classroom Time",
  pageXPs: [],
  text1: "'How do you structure your ELA block (day)?'",
  text2: "This is one of the most common questions asked in the SOR groups.",
  text3: "And it's not one for which science gives us a ton of answers.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Interventions",
  title: "Science of Reading--Interventions",
  challenge: "",
  pageXPs: [],
  text1: "The earlier we catch each child's specific issues, the better they'll progress with their class.",
  text2: "",
  text3: "",
  use_sections: true,
  sectionInfo: [{
    sectionHeading: "What Does It Look Like?",
    sectionText1: "A brief look at some of the most common ways we give young learners extra help.",
    sectionText2: "",
    sectionText3: "",
    sectionXPs: ["XP150", "XP151"]
  },
  {
    sectionHeading: "Exactly the right help for each child",
    sectionText1: "Before we offer any child extra help, it's critical to be absolutely clear the exact help they need.",
    sectionText2: "",
    sectionText3: "",
    sectionXPs: ["XP6211", "XP6212"]
  },
  {
    sectionHeading: "Using the right tools for the task.",
    sectionText1: "Again, still just getting started helping with these,...",
    sectionText2: "",
    sectionText3: "",
    sectionXPs: ["XP154", "XP155", "XP156", "XP157"]
  }],
  image1: "~/images/impact.jpg",
  image2: "~/images/InterventionEffects.png",
  closingText: "Again, it's critical to identify and implement the right interventions sooner, rather than later..",
  closingText2: "See the Level III Dyslexia page for research behind these effect sizes.",
  modal: ""
}, {
  page: "Readers",
  title: "Science of Reading: Decodable Readers",
  challenge: "Choosing Decodable Readers",
  pageXPs: ["XP204", "XP200", "XP202", "XP201"],
  text1: "The science is actually still out on the importance of decodable readers. ",
  text2: "Yet many teachers like them, and they can help guide teachers as they work through their kids' Swiss Cheese Knowledge of Phonics.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: "ModalReaders"
}, {
  page: "PreService",
  title: "Science of Reading: Preservice Programs",
  challenge: "Teachers of PreService T's",
  pageXPs: [],
  text1: "Do you teach or help guide a pre-service teacher program?",
  text2: "Here's a little more help for you.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "ProgressTracking",
  title: "Science of Reading: Learner Progress Tracking",
  challenge: "How do we track the progress as children learn to read?",
  pageXPs: ["XP165", "XP160", "XP161", "XP162", "XP163", "XP164"],
  text1: "It's critical to know that each student has mastered all of the skills and knowledge essential to reading success.",
  text2: "",
  text3: "",
  use_sections: false,
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "GettingHelp",
  title: "Science of Reading: Getting Help",
  challenge: "Where Do I Turn For Help in This, Day in and Day Out?",
  pageXPs: [],
  text1: "By far, the coolest development in K12 in 2019 was the rise of two communities of teachers arround the science of reading.",
  text2: "The first, the #ELAchat community on Twitter, had some high-energy, experienced, leaders at it's core.",
  text3: "The second, larger, and arguably sweeter group has gone viral on Facebook. A remarkable number of teachers, and parents, joined in just weeks.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Training",
  title: "Science of Reading: Teacher Training",
  challenge: "Training is Critical if We're to Eliminate Kids' Swiss Cheese Phonics Knowledge",
  pageXPs: ["XP226", "XP225", "XP220", "XP221", "XP222", "XP223", "XP224"],
  text1: "While you can train yourself in a real pinch, formal training makes things so much better.",
  text2: "It's hard to find the right, effective training. We'll do our best to help.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "ThirdGrade",
  title: "Science of Reading--3rd Grade+",
  challenge: "3rd Grade (and Up)",
  pageXPs: ["XP190", "XP191", "XP192", "XP193", "XP5504", "XP194"],
  text1: "By third grade, nearly all kids should be acing their phonemic awareness, and decoding well. What's next?",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "SwissCheese",
  title: "Science of Reading--Parmesian, Please",
  challenge: "From Swiss to Parmesian",
  pageXPs: ["XP237", "XP230", "XP231", "XP238", "XP232", "XP234", "XP235", "XP236", "XP237"],
  text1: "Those holes in phonics knowledge and/or phonological processing skills won't fix themselves.",
  text2: "And every class is different on how to address them.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Research",
  title: "Science of Reading--Research, Research!",
  challenge: "Digging in to the Research",
  pageXPs: ["XP2020", "XP2000", "XP2001", "XP2002", "XP2003"],
  text1: "Here's where we really start to dive in. What have scientists told us? In their own, original words?",
  text2: "In earlier sections, we gave a few seminal papers & experiments. But here, we really want to lay out a comprehensive view of the landscape.",
  text3: "This will be work for version 2 or 3, to be sure. Still, let's give it a start.",
  closingText: "Well! Just from these, we can see that the Science of Reading, even among scientists, is not only still evolving; its living and human nature can invite passion from the most seasoned of researchers.",
  closingText2: "We put the two models above, not to choose one approach, but to indicate that we'll all have an incomplete understanding. Many trainers will embrace a third graphic, the famous 'Scarborough's Reading Rope.'",
  closingText3: "For now, we'll leave the research section at this, and invite you to meet some of the people who give us the Science of Reading.",
  savedTExt: "Is reality more in the middle? Will practitioners and program developers use both?",
  challenge2: "The Evolving Models of Reading",
  modal: ""
}, {
  page: "ResearchConsumption",
  title: "Science of Reading--Using Research",
  challenge: "Not All Research is Created Equal. How to Tell?",
  pageXPs: ["XP2101", "XP2102", "XP2103"],
  text1: "Discussions of teaching often degenerate to very different kinds of 'peer-reviewed' papers being thrown past each other.",
  text2: "Growing an understanding of each takes some tough work.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "People",
  title: "Science of Reading--The People",
  challenge: "Science is People",
  pageXPs: [],
  text1: "Science isn't just experiments, papers, models. It's the living understanding inside the minds of those who have studied it deeply.",
  text2: "Here we'll try to meet some of those people, understand how they contribute.",
  text3: "Again, this will be work for versions 2 and 3. For now, a few.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Issues",
  title: "Science of Reading--Issues",
  challenge: "Issues, Disagreements, and Controversies",
  pageXPs: ["XP2410", "XP2402", "XP2403", "XP2404", "XP2405"],
  text1: "That now famous term 'Scientific Consensus'. What if it's not yet there?",
  text2: "Let's explore a few areas where we need more research. Or, at least, better interpretations of the existing studies.",
  text3: "Again, this will evolve more in version 2",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "History",
  title: "Science of Reading--Timeline of the Science",
  challenge: "When and how did the Science of Reading evolve?",
  pageXPs: [],
  text1: "Who discovered what; and when?",
  text2: "If we are clearer on exactly what crucial discoveries constituted the science of reading, we'll face less friction in getting its results to all children.",
  text3: "Hopefully, this will evolve into a more dynamic section of the app, with user features not yet quite imagined. ",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "English",
  title: "Science of Reading--Linguistics",
  challenge: "Just How did English become so complex?",
  pageXPs: [],
  text1: "English is just a hard language.",
  text2: "It's often difficult for people with a full command of English to grasp why others fell behind. And sometimes, SOR advocates get so enthusiastic about phonics and phonemic awareness, that they forget how hard the other parts are, too.",
  text3: "Linguistics is part of the reading teachers toolkit. Here's just a taste, while we think about what else might go here. ",
  section2: "Why is 'girl' not like 'giraffe'?",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "TrainingPrograms",
  title: "Science of Reading--Training Programs Compared",
  challenge: "All training programs differ. How?",
  pageXPs: [],
  text1: "In Level III, we looked across the complexity of the science of reading, and at it's cutting edges.",
  text2: "By their nature, training programs will try to capture this science. They'll succeed in places, lag in places, and sometimes just miss.",
  text3: "How this should be approached here is still a question. We'd love to hear your thoughts.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "PhonicsApproaches",
  title: "Science of Reading--Phonics Instructional Approaches",
  challenge: "`Phonics` can mean many things.",
  pageXPs: ["XP5003", "XP5004", "XP5007", "XP5005", "XP5006"],
  text1: "Much debate continues within the S.o.R. community as to exactly which forms of phonics instruction are most effective.",
  text2: "Why isn't 'action' spelled 'acshun'?",
  text3: "",
  closingText: "As we develop this section, we'll try to help you make sense of that debate.",
  closingText2: "",
  modal: ""
}, {
  page: "HowKidsLearn",
  title: "Science of Reading--How Children Learn to Read",
  challenge: "What Do We Know about Reading, and How Young Kids Learn to Do It?",
  pageXPs: ["XP300", "XP301", "XP303", "XP310", "XP302"],
  text1: "This ought be an entire section of the app. With fully interactive, multi-media engagement.",
  challenge2: "Who Knew, and When Did They Know It?",
  text2: "",
  challenge3: "And What, Exactly, Did They Know?",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "ComprehensionIII",
  title: "Science of Reading--Comprehension Level III",
  challenge: "Teaching to Grow Comprehension",
  use_sections: true,
  sectionInfo: [{
    sectionHeading: "Comprehension instruction IS NOT worksheets with Find the Main Idea.",
    sectionText1: "So much time and energy has been expended on teaching and measuring 'comprehension skills'. Research tells us, it doesn't help.",
    sectionText2: "",
    sectionText3: "",
    sectionXPs: ["XP5521"]
  },
  {
    sectionHeading: "Comprehension instruction IS done within a comprehensive high quality curriculum, with proper training of teachers, employing a number of proven reading strategies.",
    sectionText1: "Focus each day on rigorous, challenging texts.",
    sectionText2: "",
    sectionText3: "",
    sectionXPs: ["XP5509", "XP5512", "XP5502", "XP5503", "XP5504", "XP5507", "XP5508"]
  }],
  pageXPs: [],
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "DyslexiaIII",
  title: "Science of Reading--Reading Difficulties",
  challenge: "What Neurobiological Conditions Impede Reading?",
  pageXPs: ["XP53", "XP6003", "XP6004", "XP6005", "XP6006"],
  text1: "It's tempting to view Dyslexia as a disability. Many lawyers insist on it.",
  text2: "Yet, scientifically, it's harder to pin down. Reading difficulties present as a spectrum of conditions. Including some that are assets in other cognitive tasks.",
  text3: "Here we'll dig in to both the science, and issues of practice.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "MTSS",
  title: "Science of Reading--MTSS || RTI",
  challenge: "How do we structure learning and services that we can't deliver in the classroom?",
  pageXPs: ["XP152", "XP153"],
  text1: "",
  text2: "",
  closingText2: "",
  modal: ""
}, {
  page: "BadUglyIII",
  title: "Science of Reading--Bad, Ugly III",
  challenge: "Unbalanced Literacy: the Bad, and the Ugly.",
  pageXPs: ["XP5600", "XP5601", "XP5604", "XP111"],
  text1: "When 'Balanced Literacy' is truly balanced, it really looks a lot like the Science of Reading.",
  text2: "Yet, as practiced, it often includes some just bad concepts, ideas, and advice.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "GradSchools",
  title: "Science of Reading--Grad Schools",
  challenge: "How Can I Specialize in This?",
  pageXPs: ["XP7000"],
  text1: "Not many universites have a Dept. of Science of Reading.",
  text2: "So, where to go to study?",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "LearningScience",
  title: "Science of Reading--Science of Learning",
  challenge: "The Broader Science about Learning",
  pageXPs: ["XP2220", "XP2201", "XP2202", "XP2230", "XP2210", "XP2240"],
  text1: "There's a lot more science about how people learn.",
  text2: "Let's look at some of the basics.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "Law",
  title: "Science of Reading--I Love the Law",
  challenge: "How Can the Law Help, Hinder Schools in their S.O.R Journey?",
  pageXPs: ["XP6503", "XP6504"],
  text1: "",
  text2: "The fifty US state laboratories are experimenting with how to bring the SoR to most help kids. ",
  text3: "Let's peek in.",
  closingText: "",
  closingText2: "'I Love The Law!!' -- the mantra my law professor made us repeat.",
  modal: ""
}, {
  page: "Engineering",
  title: "S.O.R.--The Engineering of Reading Instruction",
  challenge: "No, we don't have solid science for every aspect of teaching. Neither do designers of ships, rockets, or planes.",
  pageXPs: ["XP7500"],
  text1: "Here's a typical argument for why the Science of Reading should not be followed in the classroom:",
  text2: "'The apologetics of the gaps in the science and lack of replication is what has gotten us bad policy and bad curriculum. If we aren’t careful, we’ll just repeat history. It is why there are these pendulum swings and why movements get cult reputations.'",
  text3: "It's not on its face completely untrue. But it is bad advice.",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  page: "WhatsMissing",
  title: "S.O.R.--Whats Missing From the Science",
  challenge: "And What Can We Do to Get It Done?",
  pageXPs: ["XP8000"],
  text1: "We still don't have many of the answers we should have by now.",
  text2: "In this section, we'll try to gather and sort such questions.",
  text3: "Eventually, we hope that PhD candidates and other researchers can come right to here for ideas about questions they can pursue.",
  closingText: "",
  closingText2: "",
  modal: ""
}]