export const timelineEntries = [{
  title: "In the '60's and '70's, researchers build up evidence...",
  subtitle: "for the role of decoding and phono- logical awareness.",
  id: 0,
  nestlevel: "1",
  has_subitems: true,
  subitems: [1, 10, 11],
  has_XPs: false,
  XPs: [],
  year: "",
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  title: "Jeanne Chall (founder of the Harvard Reading Lab) publishes 'Learning to Read: The Great Debate'",
  subtitle: "",
  id: 1,
  nestlevel: "2",
  subitems: [],
  has_XPs: false,
  XPs: [],
  year: "1963",
  text1: "It summarizes the different approaches to reading instruction and argues that phonics-based instruction is most effective.",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
},
{
  title: "Van Ordens Experiments",
  subtitle: "show that the primary path to reading in the brain is through sound.",
  id: 2,
  nestlevel: "1",
  has_subitems: false,
  subitems: [],
  has_XPs: true,
  XPs: ["XP70"],
  xpType: "timelineItem",
  year: "1987",
  text1: "These experiments up-ended how we think about how the brain processes text.",
  text2: "They were so contrary to previous thinking that many refused to accept them.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
},
{
  title: "Seidenberg & McClelland's simulations",
  subtitle: "support a parallel-distributed (connectionist) model, with phonological, orthographic, and semantic processor",
  id: 3,
  nestlevel: "1",
  subitems: [],
  has_XPs: true,
  XPs: ["XP8510"],
  year: "1989",
  text1: "This approach came to be known as 'statistical learning'.",
  text2: "Today, statistical learning is used in AI and machine learning; and continues to contribute to our understnading of how humans learn to read.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: "",
  url: "https://l.facebook.com/l.php?u=https%3A%2F%2Fciteseerx.ist.psu.edu%2Fviewdoc%2Fdownload%3Fdoi%3D10.1.1.127.3083%26rep%3Drep1%26type%3Dpdf%26fbclid%3DIwAR2OAlq28o9hk40P-ZMzA_pdGIh9y61z9kkkrrlfuE8xnBsutSn_HUCTjEY&h=AT0cMq3l_t348X4RPn2i6o2kw95Y2J-0FOTTA_CDmdEooKf38thZ7mM3ulV7oTGLrMNwO-UNtjd_-O57fhboKc8btmkKbpfM0WOMoWee78_Am1nKqJlXq0-CO3sx5xxYxRwrmFg&__tn__=R]-R&c[0]=AT34un42tRGCnyIXmfHpVJwhGX4SVVCjvxbI9iKBp6KZCuOUvXfSvNoMUD7g8F8K7mIkim30Vl5V_7dIs94-_B0hzQ_iM_MGLnWs9udSXzcwcrs-nLdxiCaA52zKi4LoDQC-DQW1dbsl_NZ33jqe2RigQ-vWmOn9",
}, {
  title: "Adams ...",
  subtitle: "",
  id: 4,
  nestlevel: "2",
  subitems: [],
  has_XPs: false,
  XPs: [],
  year: "1990",
  text1: "",
  text2: "Lorem ipsum dolor sit amet, eu mea vide option, ius solum augue vituperata ei. ",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  title: "Shaywitz",
  subtitle: "",
  id: 5,
  nestlevel: "2",
  subitems: [],
  has_XPs: false,
  XPs: [],
  year: "1987",
  text1: "Lorem ipsum dolor sit amet",
  text2: "Lorem ipsum dolor sit amet, eu mea vide option, ius solum augue vituperata ei. ",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  title: "Chall",
  subtitle: "",
  id: 6,
  nestlevel: "1",
  subitems: [],
  has_XPs: false,
  XPs: [],
  year: "1987",
  text1: "Lorem ipsum dolor sit amet",
  text2: "Lorem ipsum dolor sit amet, eu mea vide option, ius solum augue vituperata ei. ",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
},
{
  title: "Linnea Ehri compares ways to read with the 4 stages of reading development;",
  subtitle: "and considers implications for word-reading models",
  id: 7,
  nestlevel: "2",
  subitems: [],
  has_XPs: true,
  XPs: ["XP3002"],
  xpType: "timelineItem",
  year: "1994",
  text1: "She also gives researchers and teachers the term 'OrthographicMapping'",
  text2: "She also givers researchers and teachers the term 'OrthographicMapping'",
  text3: "",
  closingText: "",
  closingText2: "",
  url: "https://l.facebook.com/l.php?u=https%3A%2F%2Ffiles.oakland.edu%2Fusers%2Fmceneane%2Fweb%2Frdg414%2Fpdf%2Fehri15.pdf%3Ffbclid%3DIwAR0QKn7wvodqxj7Bd3qPJetvcPX-tavXiKiKPT3tqDao2VD8aFD3kI9cczw&h=AT3BG11aBxUQL-HCbijgXyPr27zsoTbjKs0a2vhriGkDJYeew2r1SIRNE_n7aOxPQz9oM2Rf51CfNURq54SSyVmKchExZ4KwnT0aea8xTziVn8p2vu-kKEDyjXLyP72DK1_hmno&__tn__=R]-R&c[0]=AT34un42tRGCnyIXmfHpVJwhGX4SVVCjvxbI9iKBp6KZCuOUvXfSvNoMUD7g8F8K7mIkim30Vl5V_7dIs94-_B0hzQ_iM_MGLnWs9udSXzcwcrs-nLdxiCaA52zKi4LoDQC-DQW1dbsl_NZ33jqe2RigQ-vWmOn9",
  modal: ""
}, {
  title: "Share tests his 'Self-Teaching' Hypothesis",
  subtitle: "",
  id: 8,
  nestlevel: "2",
  subitems: [],
  has_XPs: true,
  XPs: ["XP8532"],
  year: "1999",
  text1: "",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
},
  ,
{
  title: "Keith Stanovich show that children's reading ability is related to their phonological awareness. ",
  subtitle: "",
  id: 10,
  nestlevel: "2",
  subitems: [],
  has_XPs: false,
  XPs: [],
  xpType: "timelineItem",
  year: "1973",
  text1: "They found that children who were better at identifying and manipulating speech sounds were better readers.",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
},
{
  title: "Project Follow Through essentially validates that direct instruction is more beneficial to low-SES children than other approaches.",
  subtitle: "",
  id: 11,
  nestlevel: "2",
  subitems: [],
  has_XPs: false,
  XPs: [],
  xpType: "timelineItem",
  year: "1978",
  text1: "The largest and most expensive education program ever, it also validated a focus on foundational skills.",
  text2: "https://en.wikipedia.org/wiki/Follow_Through_(project)",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
}, {
  title: "The 44 member NICHD Reading Research Network accelerates ",
  subtitle: "its program of research to answer the big questions about equity in reading instruction.",
  id: 12,
  nestlevel: "1",
  has_subitems: false,
  subitems: [],
  has_XPs: true,
  XPs: ["XP8520"],
  year: "",
  text1: "",
  text2: "",
  text4: "This research pursues three fundamental questions about reading failure and successfully addressing it.",
  closingText: "",
  closingText2: "",
  modal: "",
  use_image: true,
  image_source: "NICHD Reading Research Network.png"
},
{
  title: "In the '90's', researchers systematically fill in the gaps",
  subtitle: "",
  id: 13,
  nestlevel: "1",
  has_subitems: true,
  subitems: [4, 7, 8],
  has_XPs: false,
  XPs: [],
  year: "",
  text1: "...often under the auspices of the NICHD Research Network.",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: ""
},
{
  title: "Dehaene, etc use fMRI to demonstrate location of Visual Word Form Area",
  subtitle: "-",
  id: 9,
  nestlevel: "1",
  subitems: [],
  has_XPs: true,
  XPs: ["XP8540"],
  xpType: "timelineItem",
  year: "2003",
  text1: "To many younger teachers, this feels like the beginning of the science.",
  text2: "But, of course, the science of reading was decades in the making.",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: "",
  url: "",
},
{
  title: "Into the 2020's, scientists continue to confirm earlier theories, resolve undecided questions, and introduce new ones.",
  subtitle: "-",
  id: 10,
  nestlevel: "1",
  subitems: [],
  has_XPs: true,
  XPs: ["XP8551"],
  xpType: "timelineItem",
  year: "2023",
  text1: "It's *still* an exciting time to do, or just watch, the science of reading development.",
  text2: "",
  text3: "",
  closingText: "",
  closingText2: "",
  modal: "",
  url: "",
}
]